version: '3.1'

networks:
  jenkins_network:

volumes:
  jenkins_workspace:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${JENKINS_HOME}

services:
  jenkins:
    build:
      context: .
      args:
        docker_compose_version: 1.23.1
        node_version: 11
        go_version: 1.11.5
    container_name: ${PROJECT_NAME}_jenkins
    hostname: ${PROJECT_NAME}_jenkins
    ports:
      - 8090:8080
      - 50001:50000
    environment:
      - JENKINS_HOME=${JENKINS_HOME}
      - JAVA_OPTS="-Djava.io.tmpdir=${JENKINS_HOME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_workspace:${JENKINS_HOME}
    networks:
      - jenkins_network
